### PR TITLE
Git/week1

### PR DESCRIPTION
**Pull request by ajgcph2019**

### CODE REVIEW

**Comment by martamatos** [comment]
Overall it's good, but i'd suggest writing more meaningful commit messages. For instance, instead of writing "Added file to repo" you could write "Added file with Chicken Roast kerala style recipe" or "Added my favorite recipe", something like that, something that when you read it you know right away what you did in that commit (or at least you have pretty good idea of what you did) :)
Does it make sense to you?

Now, can you add a fourth country to the file `countries.txt` and push again to update the pull request please?

**Comment by martamatos** [comment]
Perfect! You can now merge this branch with master :)

**Comment by ajgcph2019** [comment]
Hi Marta,
merge done.

**Comment by martamatos** [comment]
:D

**Comment by ajgcph2019** [comment]
Hi Marta,
So the homework for this week is over.We have another session for Git also
next week?

Regards,
Anna

**Comment by martamatos** [comment]
The homework for this week is over, and next week you'll have javascript.
The second git class will only happen before you start the project :)

**Comment by ajgcph2019** [comment]
Thanks for letting me know :)

**Pull request merged**
